# Generated by Django 5.1.4 on 2025-03-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
