# Generated by Django 5.1.4 on 2025-03-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_customuser_alter_plant_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
